use super::*;

#[derive(Debug, Clone)]
pub enum GerberViewerMessage
{
    OpenGerberFiles,
    GerberFilesChosen(Option<Vec<PathBuf>>),
    GerberFilesLoaded(GerberLoadBatch),
    OpenExcellonFiles,
    ExcellonFilesChosen(Option<Vec<PathBuf>>),
    ExcellonFilesLoaded(GerberLoadBatch),
    OpenAutodetectedFiles,
    AutodetectedFilesChosen(Option<Vec<PathBuf>>),
    AutodetectedFilesLoaded(GerberLoadBatch),
    OpenZipArchive,
    ZipArchiveChosen(Option<PathBuf>),
    ZipArchiveLoaded(GerberLoadBatch),
    OpenGerberJob,
    GerberJobChosen(Option<PathBuf>),
    GerberJobLoaded(GerberLoadBatch),
    ReloadAllLayers,
    LayersReloaded(signex_gerber::GerberReloadBatch),
    SelectLayer(usize),
    NextLayer,
    PreviousLayer,
    SetLayerVisible(usize, bool),
    ClearCurrentLayer,
    ClearAllLayers,
    RedrawViewport,
    ToggleSketchFlashes,
    ToggleSketchLines,
    ToggleSketchPolygons,
    ToggleGhostNegativeObjects,
    ToggleDCodeLabels,
    ToggleCompareMode,
    ToggleDimInactiveLayers,
    ZoomBy(f32),
    PanBy(iced::Vector),
    FitPage,
    ToggleLayerManager,
    ToggleLayerInformation,
    ToggleDCodeList,
    ToggleSourceView,
    SelectGridSize(usize),
    ToggleGridEditor,
    NewGridNameChanged(String),
    NewGridXChanged(String),
    NewGridYChanged(String),
    SetNewGridUnitMillimetres(bool),
    CreateGridDefinition,
    DeleteGridDefinition,
    MoveGridUp,
    MoveGridDown,
    EditGridNameChanged(String),
    EditGridXChanged(String),
    EditGridYChanged(String),
    SetEditGridUnitMillimetres(bool),
    UpdateGridDefinition,
    ToggleGridVisibility(bool),
    SetDisplayUnit(GerberDisplayUnit),
    CursorWorldPositionChanged(Option<signex_gerber::Point>),
    ToggleMeasurement,
    CaptureMeasurementPoint(signex_gerber::Point),
    ResetMeasurement,
    TogglePolarCoordinates(bool),
    ToggleFullWindowCrosshair(bool),
    SetPageSize(GerberPageSize),
    PrintVisibleLayers,
    GerberPrintFinished(Result<PathBuf, String>),
    ToggleZoomSelection,
    SetHighlightedComponent(String),
    ClearComponentHighlight,
    SetHighlightedNet(String),
    ClearNetHighlight,
    SetHighlightedAttribute(GerberAttributeValue),
    ClearAttributeHighlight,
    SetHighlightedDCode(i32),
    ClearDCodeHighlight,
    SetSelectedItem(Option<GerberItemSelection>),
    ZoomToSelection
    {
        bounds: Bounds,
        viewport: Rectangle,
    },
}
